ServerEvents.recipes(event => {

event.custom({"type":"biomancy:decomposing","ingredient":{"tag":"forge:glass/colorless"},
"nutrientsCost":1,
"processingTime":60,
"results":
[
    {
    "countRange":{"type":"uniform","max":4,"min":3},
    "item":"quark:clear_shard"
    } 
]
})

event.custom({"type":"biomancy:decomposing","ingredient":{"tag":"forge:glass/white"},
"nutrientsCost":1,
"processingTime":60,
"results":
[
{
"countRange":{"type":"uniform","max":4,"min":3},
"item":"quark:white_shard"
} 
]
})

event.custom({"type":"biomancy:decomposing","ingredient":{"tag":"forge:glass/light_blue"},
"nutrientsCost":1,
"processingTime":60,
"results":
[
{
"countRange":{"type":"uniform","max":4,"min":3},
"item":"quark:light_blue_shard"
} 
]
})

event.custom({"type":"biomancy:decomposing","ingredient":{"tag":"forge:glass/cyan"},
"nutrientsCost":1,
"processingTime":60,
"results":
[
{
"countRange":{"type":"uniform","max":4,"min":3},
"item":"quark:cyan_shard"
} 
]
})

event.custom({"type":"biomancy:decomposing","ingredient":{"tag":"forge:glass/blue"},
"nutrientsCost":1,
"processingTime":60,
"results":
[
{
"countRange":{"type":"uniform","max":4,"min":3},
"item":"quark:blue_shard"
} 
]
})

event.custom({"type":"biomancy:decomposing","ingredient":{"tag":"forge:glass/red"},
"nutrientsCost":1,
"processingTime":60,
"results":
[
{
"countRange":{"type":"uniform","max":4,"min":3},
"item":"quark:red_shard"
} 
]
})

event.custom({"type":"biomancy:decomposing","ingredient":{"tag":"forge:glass/yellow"},
"nutrientsCost":1,
"processingTime":60,
"results":
[
{
"countRange":{"type":"uniform","max":4,"min":3},
"item":"quark:yellow_shard"
} 
]
})

event.custom({"type":"biomancy:decomposing","ingredient":{"tag":"forge:glass/pink"},
"nutrientsCost":1,
"processingTime":60,
"results":
[
{
"countRange":{"type":"uniform","max":4,"min":3},
"item":"quark:pink_shard"
} 
]
})

event.custom({"type":"biomancy:decomposing","ingredient":{"tag":"forge:glass/cyan"},
"nutrientsCost":1,
"processingTime":60,
"results":
[
{
"countRange":{"type":"uniform","max":4,"min":3},
"item":"quark:cyan_shard"
} 
]
})

event.custom({"type":"biomancy:decomposing","ingredient":{"tag":"forge:glass/orange"},
"nutrientsCost":1,
"processingTime":60,
"results":
[
{
"countRange":{"type":"uniform","max":4,"min":3},
"item":"quark:orange_shard"
} 
]
})

event.custom({"type":"biomancy:decomposing","ingredient":{"tag":"forge:glass/purple"},
"nutrientsCost":1,
"processingTime":60,
"results":
[
{
"countRange":{"type":"uniform","max":4,"min":3},
"item":"quark:purple_shard"
} 
]
})

event.custom({"type":"biomancy:decomposing","ingredient":{"tag":"forge:glass/magenta"},
"nutrientsCost":1,
"processingTime":60,
"results":
[
{
"countRange":{"type":"uniform","max":4,"min":3},
"item":"quark:magenta_shard"
} 
]
})

event.custom({"type":"biomancy:decomposing","ingredient":{"tag":"forge:glass/black"},
"nutrientsCost":1,
"processingTime":60,
"results":
[
{
"countRange":{"type":"uniform","max":4,"min":3},
"item":"quark:black_shard"
} 
]
})

event.custom({"type":"biomancy:decomposing","ingredient":{"tag":"forge:glass/brown"},
"nutrientsCost":1,
"processingTime":60,
"results":
[
{
"countRange":{"type":"uniform","max":4,"min":3},
"item":"quark:brown_shard"
} 
]
})

event.custom({"type":"biomancy:decomposing","ingredient":{"tag":"forge:glass/green"},
"nutrientsCost":1,
"processingTime":60,
"results":
[
{
"countRange":{"type":"uniform","max":4,"min":3},
"item":"quark:green_shard"
} 
]
})

event.custom({"type":"biomancy:decomposing","ingredient":{"tag":"forge:glass/lime"},
"nutrientsCost":1,
"processingTime":60,
"results":
[
{
"countRange":{"type":"uniform","max":4,"min":3},
"item":"quark:lime_shard"
} 
]
})

event.custom({"type":"biomancy:decomposing","ingredient":{"tag":"forge:glass/gray"},
"nutrientsCost":1,
"processingTime":60,
"results":
[
{
"countRange":{"type":"uniform","max":4,"min":3},
"item":"quark:gray_shard"
} 
]
})

event.custom({"type":"biomancy:decomposing","ingredient":{"tag":"forge:glass/light_gray"},
"nutrientsCost":1,
"processingTime":60,
"results":
[
{
"countRange":{"type":"uniform","max":4,"min":3},
"item":"quark:light_gray_shard"
} 
]
})

event.custom({"type":"biomancy:decomposing","ingredient":{"tag":"quark:dirty_glass"},
"nutrientsCost":1,
"processingTime":60,
"results":
[
{
"countRange":{"type":"uniform","max":4,"min":3},
"item":"quark:dirty_shard"
} 
]
})

})