
[Modifiers]
	#Use True to eable increasing difficulty by in game time. Warning: using /time set command will change the difficulty!
	Enable = true
	#Use True to eable increasing mobs' health by time.
	"Enable Health Changes by Time" = true
	#How many extra health will mobs gain for each 5 mins(6000 ticks) by adding.
	"Health Modifier(add)" = 0.0
	#How many extra health will mobs gain for each 5 mins by multiplying.
	"Health Modifier(multiply)" = 0.01
	#How many extra health will mobs gain for each 5 mins by multiplying after all other calculations.
	"Health Modifier(multiply_base )" = 0.0
	#Use True to eable increasing mobs' damage by time
	"Enable Damage Changes by Time" = true
	#same as health, but changes in damage
	"Damage Modifier(add)" = 0.0
	"Damage Modifier(multiply)" = 0.01
	"Damage Modifier(multiply_base)" = 0.0
	"Enable Armor Changes by Time" = true
	"Armor Modifier(add)" = 0.0
	"Armor Modifier(multiply)" = 0.01
	"Armor Modifier(multiply_base)" = 0.0
	"Enable Armor Toughness Changes by Time" = true
	"Armor Toughness Modifier(add)" = 0.0
	"Armor Toughness Modifier(multiply)" = 0.0
	"Armor Toughness Modifier(multiply_base)" = 0.0

