
[Modifiers]
	#Use True to eable increasing difficulty by entering new dimensions.
	Enable = false
	"Enable Health Changes by Dimensions" = true
	"Health Modifier(add)" = 0.0
	"Health Modifier(multiply)" = 0.01
	"Health Modifier(multiply_base )" = 0.0
	"Enable Damage Changes by Time" = true
	"Damage Modifier(add)" = 0.0
	"Damage Modifier(multiply)" = 0.01
	"Damage Modifier(multiply_base)" = 0.0
	"Enable Armor Changes by Time" = true
	"Armor Modifier(add)" = 0.0
	"Armor Modifier(multiply)" = 0.01
	"Armor Modifier(multiply_base)" = 0.0
	"Enable Armor Toughness Changes by Time" = true
	"Armor Toughness Modifier(add)" = 0.0
	"Armor Toughness Modifier(multiply)" = 0.0
	"Armor Toughness Modifier(multiply_base)" = 0.0

