
["Harder Farther Control Values"]

	["Harder Farther Control Values"."Debug Settings"]
		#Debug Level: 0 = Off, 1 = Log, 2 = Chat+Log
		#Range: 0 ~ 2
		debugLevel = 0

	["Harder Farther Control Values"."HarderFarther Settings"]
		#Only in minecraft Overworld (true) 
		onlyOverworld = true
		#Dimension Omit List
		dimensionOmitList = ["minecraft:the_nether", "minecraft:the_end"]
		#boostMaxDistance: Distance til Maximum Boost Values Applied
		#Range: 1000 ~ 6000000
		boostMaxDistance = 50000
		#boostMinDistance: Distance til Boost Values Start.  Should be less than boostMaxDistance
		#Range: 64 ~ 1000000
		boostMinDistance = 10000
		#Worldspawn Safe Distance: No Hostile Creatures Will Spawn In this Range
		#Range: 1 ~ 1024
		safeDistance = 64
		#minimumSafeAltitude: Mobs are 6% tougher below this altitude. 
		#Range: -32 ~ 64
		minimumSafeAltitude = 32
		#maximumSafeAltitude: Mobs are 9% tougher above this altitude.
		#Range: 65 ~ 256
		maximumSafeAltitude = 99

	["Harder Farther Control Values"."Boost Settings"]
		#Boost Max Hit Points (Percent) 
		#Range: 0 ~ 30000000
		hpMaxBoost = 200
		#Boost Movement Speed (Percent). Very sensative setting. Over 50 kinda ridiculous 
		#Range: 0 ~ 999
		speedBoost = 20
		#Boost Attack Damage (percent).  Mobs base damage is about 3 points + 2 for hard mode.
		#Range: 0 ~ 30000000
		atkDmgBoost = 100
		#Boost Knockback Resistance (Percent) over 100 has no additional effect.
		#Range: 0 ~ 999
		knockbackBoost = 95

	["Harder Farther Control Values"."Fog Color Settings"]
		#Fog Setting: 0=off, 1 only grim citadels and life points, 2=everywhere 
		#Range: 0 ~ 2
		fogSetting = 1
		#fogRedPercent : Fog Red Component Multiplier
		#Range: 0.0 ~ 1.0
		fogRedPercent = 0.95
		#fogBluePercent : Fog Blue Component Multiplier
		#Range: 0.0 ~ 1.0
		fogBluePercent = 0.05
		#fogGreenPercent : Fog Green Component Multiplier
		#Range: 0.0 ~ 1.0
		fogGreenPercent = 0.05

